parameters:
  ps_eventbus.proxy_api_url: "https://eventbus-proxy.psessentials.net"
  ps_eventbus.sync_api_url: "https://eventbus-sync.psessentials.net"
  ps_eventbus.sentry_dsn: "https://sentry-id@stuff.ingest.sentry.io/stuff"
  ps_eventbus.sentry_env: "development"