# Note: this file is here for documentation purpose
# It will be overrided by the Makefile
parameters:
  ps_eventbus.proxy_api_url: "http://cloudsync-mock-test:3333"
  ps_eventbus.sync_api_url: "http://cloudsync-mock-test:3232"
  ps_eventbus.sentry_dsn: "https://sentry-id@stuff.ingest.sentry.io/stuff"
  ps_eventbus.sentry_env: "development"

# ps_eventbus.proxy_api_url: "https://eventbus-proxy.psessentials.net"
#  ps_eventbus.sync_api_url: "https://eventbus-sync.psessentials.net"
#  ps_eventbus.sentry_dsn: "https://sentry-id@stuff.ingest.sentry.io/stuff"
#  ps_eventbus.sentry_env: "development"