services:
  PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandlerInterface: '@PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandler'

  PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandler:
    class: PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandler
    arguments:
      - '@ps_eventbus'
      - '@PrestaShop\Module\PsEventbus\Config\Env'
      - '@PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'

